"use client";
import { useEffect, useState } from "react";

type Item = any;
const sections = [
  ["announcements", "📢 Announcements"], ["assignments", "📝 Assignments"], ["exams", "📅 Exams & Quizzes"], ["materials", "📚 Study Materials"], ["polls", "🗳️ Class Polls"]
] as const;

export default function HubPage() {
<<<<<<< HEAD
  const [type, setType] = useState<string>("announcements"); const [items, setItems] = useState<Item[]>([]); const [msg, setMsg] = useState(""); const [openPoll, setOpenPoll] = useState<string | null>(null);  const [form, setForm] = useState<any>({});
=======
  const [type, setType] = useState<string>("announcements"); const [items, setItems] = useState<Item[]>([]); const [msg, setMsg] = useState(""); const [openPoll, setOpenPoll] = useState<string | null>(null);
  const [form, setForm] = useState<any>({});
>>>>>>> 4c776aa (Premium portal UI and CR management updates)
  async function load() { const r = await fetch(`/api/class-hub?type=${type}`); const d = await r.json(); setItems(d.items || []); }
  useEffect(() => { load(); setForm({}); }, [type]);
  async function add(e:any) { e.preventDefault(); setMsg(""); const r=await fetch(`/api/class-hub?type=${type}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json(); if(!r.ok){setMsg(d.error||"Could not save");return;} setForm({}); setMsg("Published successfully."); load(); }
  async function del(id:string){if(!confirm("Delete this item?"))return; await fetch(`/api/class-hub?type=${type}&id=${id}`,{method:"DELETE"});load();}
  const input=(key:string,placeholder:string,typex="text")=><input type={typex} value={form[key]||""} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})} required/>;
  return <div><div className="card"><h2 style={{marginTop:0}}>✨ Class Hub</h2><p className="hint">Manage class content here. Everything published appears on the Student Portal.</p><div className="nav-tabs" style={{margin:"12px -18px -18px",overflowX:"auto"}}>{sections.map(([k,l])=><button key={k} className={`nav-tab ${type===k?"active":""}`} onClick={()=>setType(k)}>{l}</button>)}</div></div>
    <div className="card"><h3 style={{marginTop:0}}>Create {type}</h3><form onSubmit={add}><div className="field">{type==="announcements"&&<>{input("title","Announcement title")}<textarea value={form.body||""} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Write announcement..." required/><select value={form.priority||"NORMAL"} onChange={e=>setForm({...form,priority:e.target.value})}><option>NORMAL</option><option>IMPORTANT</option><option>URGENT</option></select></>}{type==="assignments"&&<>{input("title","Assignment title")}{input("subject","Subject")}{input("dueDate","Due date","datetime-local")}<textarea value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description"/></>}{type==="exams"&&<>{input("title","Exam / quiz title")}{input("subject","Subject")}{input("date","Date","datetime-local")}{input("startTime","Time, e.g. 10:00 AM")}{input("room","Room / venue")}</>}{type==="materials"&&<>{input("title","Material title")}{input("subject","Subject")}{input("url","Google Drive / PDF / website link","url")}<textarea value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Short description"/></>}{type==="polls"&&<>{input("question","Poll question")}{input("options","Options separated by | e.g. Monday | Tuesday | Wednesday")}</>}</div>{msg&&<div className="success-text">{msg}</div>}<button className="btn btn-primary" type="submit">Publish to Students</button></form></div>
<<<<<<< HEAD
    <div className="card"><h3 style={{marginTop:0}}>Published ({items.length})</h3>{items.length===0?<div className="empty-state">Nothing published yet.</div>:items.map((x:Item)=><div className="student-row" key={x.id}><div style={{width:"100%"}}><div className="name">{x.title||x.question}</div><div className="meta">{x.subject||x.priority||new Date(x.createdAt).toLocaleString()}{type==="polls" ? ` · ${x.voteCount || 0} vote${(x.voteCount || 0)===1?"":"s"}` : ""}</div>{type==="polls" && <div style={{marginTop:10}}><button className="btn btn-secondary btn-sm" onClick={()=>setOpenPoll(openPoll===x.id?null:x.id)}>{openPoll===x.id ? "Hide Vote Records" : "View Vote Records"}</button>{openPoll===x.id && <div style={{marginTop:10,overflowX:"auto",border:"1px solid var(--line)",borderRadius:10}}><div style={{padding:"10px 12px",fontWeight:700,background:"var(--soft)"}}>🗳️ Vote Records — {x.votes?.length || 0} votes</div>{x.votes?.length ? <table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr><th style={{textAlign:"left",padding:8}}>Student Name</th><th style={{textAlign:"left",padding:8}}>Roll No.</th><th style={{textAlign:"left",padding:8}}>Vote</th><th style={{textAlign:"left",padding:8}}>Date / Time</th></tr></thead><tbody>{x.votes.map((v:any)=><tr key={v.id}><td style={{padding:8,borderTop:"1px solid var(--line)"}}>{v.student?.fullName || "Unknown"}</td><td style={{padding:8,borderTop:"1px solid var(--line)"}}>{v.student?.iubId || v.student?.regNumber || "—"}</td><td style={{padding:8,borderTop:"1px solid var(--line)"}}><strong>{v.option}</strong></td><td style={{padding:8,borderTop:"1px solid var(--line)"}}>{new Date(v.createdAt).toLocaleString()}</td></tr>)}</tbody></table> : <div className="hint" style={{padding:12}}>No students have voted yet.</div>}</div>}</div>}</div><button className="btn btn-danger btn-sm" onClick={()=>del(x.id)}>Delete</button></div>)}</div>  </div>
=======
    <div className="card"><h3 style={{marginTop:0}}>Published ({items.length})</h3>{items.length===0?<div className="empty-state">Nothing published yet.</div>:items.map((x:Item)=><div className="student-row" key={x.id}><div style={{width:"100%"}}><div className="name">{x.title||x.question}</div><div className="meta">{x.subject||x.priority||new Date(x.createdAt).toLocaleString()}{type==="polls" ? ` · ${x.voteCount || 0} vote${(x.voteCount || 0)===1?"":"s"}` : ""}</div>{type==="polls" && <div style={{marginTop:10}}><button className="btn btn-secondary btn-sm" onClick={()=>setOpenPoll(openPoll===x.id?null:x.id)}>{openPoll===x.id ? "Hide Vote Records" : "View Vote Records"}</button>{openPoll===x.id && <div style={{marginTop:10,overflowX:"auto",border:"1px solid var(--line)",borderRadius:10}}><div style={{padding:"10px 12px",fontWeight:700,background:"var(--soft)"}}>🗳️ Vote Records — {x.votes?.length || 0} votes</div>{x.votes?.length ? <table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr><th style={{textAlign:"left",padding:8}}>Student Name</th><th style={{textAlign:"left",padding:8}}>Roll No.</th><th style={{textAlign:"left",padding:8}}>Vote</th><th style={{textAlign:"left",padding:8}}>Date / Time</th></tr></thead><tbody>{x.votes.map((v:any)=><tr key={v.id}><td style={{padding:8,borderTop:"1px solid var(--line)"}}>{v.student?.fullName || "Unknown"}</td><td style={{padding:8,borderTop:"1px solid var(--line)"}}>{v.student?.iubId || v.student?.regNumber || "—"}</td><td style={{padding:8,borderTop:"1px solid var(--line)"}}><strong>{v.option}</strong></td><td style={{padding:8,borderTop:"1px solid var(--line)"}}>{new Date(v.createdAt).toLocaleString()}</td></tr>)}</tbody></table> : <div className="hint" style={{padding:12}}>No students have voted yet.</div>}</div>}</div>}</div><button className="btn btn-danger btn-sm" onClick={()=>del(x.id)}>Delete</button></div>)}</div>
  </div>
>>>>>>> 4c776aa (Premium portal UI and CR management updates)
}
