"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { signOut } from "next-auth/react";
import { useEffect } from "react";
const items=[
 {href:"/portal",label:"Home",icon:"⌂"},{href:"/portal/analytics",label:"Analytics",icon:"◒"},{href:"/portal/schedule",label:"Schedule",icon:"▦"},{href:"/portal/notifications",label:"Alerts",icon:"♢"},{href:"/portal/requests",label:"Requests",icon:"＋"}
];
export default function StudentNav(){const p=usePathname(); useEffect(()=>{(async()=>{try{if(!('serviceWorker' in navigator)||!('PushManager' in window))return; const reg=await navigator.serviceWorker.register('/sw.js'); const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if(!key||Notification.permission==='denied')return; const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission(); if(permission!=='granted')return; const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))}); await fetch('/api/push/subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({endpoint:sub.endpoint,keys:{p256dh:btoa(String.fromCharCode(...new Uint8Array(sub.getKey('p256dh')!))),auth:btoa(String.fromCharCode(...new Uint8Array(sub.getKey('auth')!)))}})});}catch{}})()},[]); return <><header className="student-pro-topbar"><div><div className="student-pro-brand">FIFTH FIVE <span>STUDENT</span></div><div className="student-pro-sub">BS Information Technology · 5TH-5M</div></div><button className="student-pro-logout" onClick={()=>signOut({callbackUrl:"/login"})}>Log out</button></header><nav className="student-pro-nav">{items.map(x=><Link key={x.href} className={p===x.href?"active":""} href={x.href}><b>{x.icon}</b><span>{x.label}</span></Link>)}</nav></>}
